name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run Maven Build (reusable)
        uses: ./.github/actions/maven-build

      - name: Deploy to server (example)
        run: |
          echo "Deploying application..."
          # scp/rsync/kubectl commands go here
